version: '3.8'

services:
  app:
    build: .
    container_name: movie-recommendation-app
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - quadrant
    volumes:
      - ./:/app

  quadrant:
    image: "qdrant/qdrant:latest"
    container_name: quadrant-db
    ports:
      - "6333:6333"
    volumes:
      - quadrant_data:/qdrant/storage

volumes:
  quadrant_data: 