[project]
name = "movie-recommendation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.115.13",
    "openai>=1.88.0",
    "polars>=1.31.0",
    "python-dotenv>=1.1.0",
    "requests>=2.32.4",
]
